=== SamiraShrestha05/SamiraShreatha_51-WebLabReport/lab3/q4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


  <xs:element name="Library">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Book" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Title" type="xs:string"/>
              <xs:element name="PageNo" type="xs:positiveInteger"/>
              <xs:element name="Price">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="PriceType">
                      <xs:attribute name="currency" use="required">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="NPR"/>
                            <xs:enumeration value="INR"/>
                            <xs:enumeration value="USD"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="Author" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Name">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="FirstName" type="xs:string"/>
                          <xs:element name="MiddleName" type="xs:string"/>
                          <xs:element name="LastName" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Phone" type="xs:string"/>
                    <xs:element name="Email" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="title" default="ms">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="mr"/>
                        <xs:enumeration value="ms"/>
                        <xs:enumeration value="mrs"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="ISBN" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

 
  <xs:simpleType name="PriceType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="600"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== SamiraShrestha05/SamiraShreatha_51-WebLabReport/lab3/q4.xml
<?xml version="1.0" encoding="UTF-8"?>
<Library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="q4.xsd">

    <Book ISBN="978-1-23456-789-0">
        <Title>Learning XML</Title>
        <PageNo>350</PageNo>
        <Price currency="USD">45.99</Price>
        <Author title="mr">
            <Name>
                <FirstName>John</FirstName>
                <MiddleName>Andrew</MiddleName>
                <LastName>Doe</LastName>
            </Name>
            <Phone>1234567890</Phone>
            <Email>john@example.com</Email>
        </Author>
        <Author>
            <Name>
                <FirstName>Jane</FirstName>
                <MiddleName>Marie</MiddleName>
                <LastName>Smith</LastName>
            </Name>
            <Phone>9876543210</Phone>
            <Email>jane@example.com</Email>
        </Author>
    </Book>

</Library>
