=== SamiraShrestha05/SamiraShreatha_51-WebLabReport/lab3/q5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


  <xs:element name="Students">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Student" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>

             
              <xs:element name="Name">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="FirstName" type="xs:string"/>
                    <xs:element name="MiddleName" type="xs:string" minOccurs="0"/>
                    <xs:element name="LastName" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

             
              <xs:element name="Email">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>

           
              <xs:element name="Phone">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="9[78][0-9]{8}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>

             
              <xs:element name="Address" maxOccurs="2">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="type" use="required">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="permanent"/>
                            <xs:enumeration value="temporary"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>

             
              <xs:element name="DOB">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:date">
                      <xs:attribute name="type" use="required">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="AD"/>
                            <xs:enumeration value="BS"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>

            </xs:sequence>
            <xs:attribute name="rollno" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== SamiraShrestha05/SamiraShreatha_51-WebLabReport/lab3/q5.xml
<?xml version="1.0" encoding="UTF-8"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="q5.xsd">

    <Student rollno="101">
        <Name>
            <FirstName>Shreya</FirstName>
            <MiddleName>R</MiddleName>
            <LastName>Thapa</LastName>
        </Name>
        <Email>shreya.thapa@example.com</Email>
        <Phone>9812345678</Phone>
        <Address type="permanent">Kathmandu, Nepal</Address>
        <Address type="temporary">Lalitpur, Nepal</Address>
        <DOB type="AD">2000-12-15</DOB>
    </Student>

    <Student rollno="102">
        <Name>
            <FirstName>Ravi</FirstName>
            <LastName>Sharma</LastName>
        </Name>
        <Email>ravi.sharma@example.com</Email>
        <Phone>9711122233</Phone>
        <Address type="permanent">Pokhara, Nepal</Address>
        <DOB type="BS">2057-05-01</DOB>
    </Student>

</Students>
